import type { Metadata } from "next";
import { Manrope} from "next/font/google";
import "./globals.css";

import FlyingAnimation from "@/components/animation/FlyingAnimaion";
import ModalManager from "@/components/modals/ModalManager";
import GlobalAlert from "@/components/ui/GlobalAlert";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import ScrollLock from "@/components/scroll-lock/scroll-lock";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body suppressHydrationWarning>
        <ScrollLock/>
      <GlobalAlert />
      <Navbar/>
     <main>
     {children}
     </main>
     <FlyingAnimation/>
     <ModalManager/>
     <Footer/>
        </body>
    </html>
  );
}
